### ISSUE TITLE
How to Access dfinity service from my Backend

### ISSUE THREAD

**Issue by SalemCode8** [dfinity/docs#260]
As is our first use of dfinity and motoko I need to use it as microservice with my own backend so it'll be storage for the sensitive data.

I Searched the whole internet on how can I send request to motoko project but I didn't find anything helpful.

**Comment by hansl** [comment]
Hi @SalemCode8,

This seems more like a discussion for our forum. You can create an account there if you don't have one yet; https://forum.dfinity.org.

Please specify which language you're using for your backend and where it is hosted (cloud services?). We have agent code for JavaScript and Rust, so that's easy, but anything else might require more discussion.

Thanks!

**Comment by hansl** [comment]
I'm going to close this as answered, but please feel free to create new issues if you have docs questions.
