### ISSUE TITLE
Edit this page links broken on all docs

### ISSUE THREAD

**Issue by sixhobbits** [dfinity/docs#506]
**Describe the bug**
The Edit button on each docs page doesn't work as it links to the `/master/` branch instead of `/main/`.

For example, on the getting-started page, it links to 

`https://github.com/dfinity/docs/edit/master/modules/quickstart/pages/quickstart-intro.adoc`

but should link to 

`https://github.com/dfinity/docs/edit/main/modules/quickstart/pages/quickstart-intro.adoc`

**To Reproduce**
1. Visit any documentation page.
2. Press the "edit this page" button
3. View the 404 error on GitHub.

**Expected behavior**
1. Visit any documentation page
2. Click the "edit this page button"
3. Get taken to the edit view on GitHub for that page.

**Screenshots**
<img width="1205" alt="grafik" src="https://user-images.githubusercontent.com/2641205/120553792-377acd80-c3f9-11eb-8ba1-53df51841a2e.png">

<img width="1163" alt="grafik" src="https://user-images.githubusercontent.com/2641205/120553915-5da06d80-c3f9-11eb-82ac-fb5ae42652cc.png">

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
I *think* this can be fixed by changing `master` to `main` in the `antora.yml`file, but I was unable to build the docs locally to verify this. The contributing page mentions a page called `antora-playbook.yml` "in another repository" but doesn't say which. The SDK repository references https://github.com/dfinity-lab/dfinity-docs-playbook but that does not exist (or is private).

**Comment by lsgunnlsgunn** [comment]
I didn't have this error. When I click the Edit icon, I get what I expect:
https://github.com/dfinity/docs/edit/main/modules/token-holders/pages/self-custody-quickstart.adoc
![image](https://user-images.githubusercontent.com/44206363/120710254-c8da5600-c472-11eb-8ef1-7984a8e2f4c0.png)

The name used in the antora.yml file is just a label and not related to the name of the branch in the repo (I know it's a little confusing, but a real pain to change when docs are stretched across multiple repos).
There are a couple of source repos that have special handling that might break the Edit functionality, but that should be the exception rather than the rule.
